# URI for database connection, leave empty if using address and credential settings directly
# mongodb的配置,和IM server使用的是一个数据库
# MongoDB 连接的 URI（统一资源标识符）。如果使用 URI 方式连接数据库，可以在这里填写完整的 MongoDB 连接字符串
uri: "mongodb://openIM:openIM123@localhost:37017/openim_v3?authSource=openim_v3&directConnection=true&replicaSet=rs0"
# List of MongoDB server addresses
# MongoDB 服务器的地址列表。如果未使用 uri，则需要在这里指定 MongoDB 服务器的地址和端口
address: [localhost:37017]
# Name of the database
# 数据库名称
database: openim_v3
# Username for database authentication
# 数据库的操作用户
username: openIM
# Password for database authentication
# 数据库的操作用户的密码
password: openIM123
# Authentication source for database authentication, if use root user, set it to admin
# 认证源数据库。如果使用的是 MongoDB 的超级用户（如 root），则需要设置为 admin
authSource: openim_v3
# Maximum number of connections in the connection pool
# 连接池大小
maxPoolSize: 100
# Maximum number of retry attempts for a failed database connection
# 连接重试次数
maxRetry: 10
# TLS configuration for MongoDB connection
# MongoDB TLS 加密连接配置
tls:
  # Enable or disable TLS encryption
  # 是否启用 TLS 加密连接
  enableTLS: false
  # Path to CA certificate file
  # CA 证书文件路径
  caCrt: ""
  # Path to client certificate file
  # 客户端证书文件路径
  clientCrt: ""
  # Path to client private key file
  # 客户端私钥文件路径
  clientKey: ""
  # Password for encrypted client private key (if applicable)
  # 客户端私钥密码（如果私钥文件有加密）
  clientKeyPwd: ""
  # Skip TLS certificate verification (not recommended for production)
  # 跳过 TLS 证书验证（生产环境不推荐）
  insecureSkipVerify: false
